site_name: Anomeda Python Package

nav:
  - Overview: index.md 
  - User Guide: user_guide.md 
  - Docs: api_reference.md
  
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_section_style: list
            docstring_style: numpy
            show_signature_annotations: true
            show_source: false
