site_name: Anomeda Python Package

nav:
  - Overview: index.md 
  - User Guide: user_guide.md 
  - Docs: api_reference.md
  
exclude_docs: |
  *.py

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_section_style: list
            docstring_style: numpy
            show_signature_annotations: true
            show_source: false
            paths: [src]
