site_name: Anomeda Python Package

nav:
  - Overview: index.md 
  - Usage: user_guide.md 
  - API Reference: api_reference.md
  
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["src/anomeda", "src"]
          options:
            docstring_section_style: list
            docstring_style: numpy
            show_signature_annotations: true
            show_source: false
            filters:
            - "!^_"
            - "!^__"
            - "!linreg"
            - "!NotFittedError"
