# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
  install:
  - requirements: docs/requirements.txt
  
site_name: Anomeda Python Package

nav:
  - Overview: index.md 
  - User Guide: user_guide.md 
  - Docs: api_reference.md
    - Another page: api/to_discrete_values.md 
#    -  anomeda._to_discrete_values: api/to_discrete_values.md 
#    -  anomeda.DataFrame: api/dataframe.md 
#      -  anomeda.DataFrame.aspandas: api/dataframe/aspandas.md 
#      -  anomeda.DataFrame.copy: api/dataframe/copy.md 
#      -  anomeda.DataFrame.mod_data: api/dataframe/mod_data.md 
#      -  anomeda.DataFrame.get_discretization_mapping: api/dataframe/get_discretization_mapping.md 
#      -  anomeda.DataFrame.set_discretization_mapping: api/dataframe/set_discretization_mapping.md 
#      -  anomeda.DataFrame.get_measures_names: api/dataframe/get_measures_names.md 
#      -  anomeda.DataFrame.set_measures_names: api/dataframe/set_measures_names.md 
#      -  anomeda.DataFrame.get_measures_types: api/dataframe/get_measures_types.md 
#      -  anomeda.DataFrame.set_measures_types: api/dataframe/set_measures_types.md 
#      -  anomeda.DataFrame.get_discretized_measures: api/dataframe/get_discretized_measures.md 
#      -  anomeda.DataFrame.set_discretized_measures: api/dataframe/set_discretized_measures.md 
#      -  anomeda.DataFrame.get_index_name: api/dataframe/get_index_name.md 
#      -  anomeda.DataFrame.set_index_name: api/dataframe/set_index_name.md 
#      -  anomeda.DataFrame.get_metric_name: api/dataframe/get_metric_name.md 
#      -  anomeda.DataFrame.set_metric_name: api/dataframe/set_metric_name.md 
#      -  anomeda.DataFrame.get_agg_func: api/dataframe/get_agg_func.md 
#      -  anomeda.DataFrame.set_agg_func: api/dataframe/set_agg_func.md 
#    -  anomeda.describe_trend: api/describe_trend.md 
#    -  anomeda.describe_trends_by_clusters: api/describe_trends_by_clusters.md 
#    -  anomeda.describe_variance_by_clusters: api/describe_variance_by_clusters.md 
#    -  anomeda.explain_values_difference: api/explain_values_difference.md 
#    -  anomeda.explain_variance_difference: api/explain_variance_difference.md 
#    -  anomeda.find_anomalies: api/find_anomalies.md 
#    -  anomeda.find_anomalies_by_clusters: api/find_anomalies_by_clusters.md 